compute_mode: 'GPU'  # Can be 'cpu', 'GPU' supported by macOS, 'cuda' #cuda support still under development #if you can avoid using cpu please do
enable_plots: true
clustering_threshold: 2
input_directory: '../aligned'
output_file: '../outputs/output.txt'
rmsd_csv_file: '../outputs/rmsd.csv'
graph_output_path: "../outputs/"  # Directory to save plots
ligand_residue: 'FMN' #set based on ligand name in the pdb file